# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Admiral < Formula
  desc "Admiral CLI - Platform Orchestrator"
  homepage "https://admiral.io/"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.3.0/admiral-v0.3.0_darwin_x86_64.tar.gz"
      sha256 "4b08057b3062f2e0b0385afeb53adfdbb86d7835a612d5e5217ecf1f92e792ba"

      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.3.0/admiral-v0.3.0_darwin_arm64.tar.gz"
      sha256 "25351bdc7f0178c5bba9cf22854d008968dc1a73b05f0d421517b8b41163de45"

      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.3.0/admiral-v0.3.0_linux_x86_64.tar.gz"
      sha256 "b44fabb72a2b2b104b0d144bc4409e31088a2d566853bce716070b738d6553fb"
      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.3.0/admiral-v0.3.0_linux_arm64.tar.gz"
      sha256 "0c0d4303f2a1f5def692312deffb63bb1f7d55da0d7a0a4cbf320e743e8f854c"
      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end
end
