# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Admiral < Formula
  desc "Admiral CLI - Platform Orchestrator"
  homepage "https://admiral.io/"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.2.0/admiral-v0.2.0_darwin_x86_64.tar.gz"
      sha256 "99d35dd039dfeb5ae57d255254053c9f06454e88cc2b1f2607d00292da0528fa"

      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.2.0/admiral-v0.2.0_darwin_arm64.tar.gz"
      sha256 "13b1495318347dfff449a9fc85ffbf91a3b4ae1cb7a49dff12c7233be4575082"

      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.2.0/admiral-v0.2.0_linux_x86_64.tar.gz"
      sha256 "bab2a991bd5ef4c0c9784998d877cd61b4c803ba67431f9e8858bd58fa4c8634"
      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/admiral-io/admiral-cli/releases/download/v0.2.0/admiral-v0.2.0_linux_arm64.tar.gz"
      sha256 "f7719660d75d3e2acf1a4e9ac7f19ae79bf017bde844bd27d3af40b629e71562"
      define_method(:install) do
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end
end
