# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdmiralServer < Formula
  desc "Admiral - Platform Orchestrator"
  homepage "https://admiral.io/"
  version "0.0.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/admiral-io/admiral/releases/download/v0.0.1/admiral-server-v0.0.1_darwin_x86_64.tar.gz"
      sha256 "673aa6c8beccaac086fbbb7bd89dcc66f5990553196dc8a748d272c0c01fc20a"

      define_method(:install) do
        bin.install "admiral-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/admiral-io/admiral/releases/download/v0.0.1/admiral-server-v0.0.1_darwin_arm64.tar.gz"
      sha256 "c87e20ba309de8ab0b3499f8d62e887c182d937f4bf87d4c5e2bd6fef1c0926f"

      define_method(:install) do
        bin.install "admiral-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/admiral-io/admiral/releases/download/v0.0.1/admiral-server-v0.0.1_linux_x86_64.tar.gz"
      sha256 "2483587133949c2adea7a0370aa80e1ea461a2115c92b6c59c76659340851412"
      define_method(:install) do
        bin.install "admiral-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/admiral-io/admiral/releases/download/v0.0.1/admiral-server-v0.0.1_linux_arm64.tar.gz"
      sha256 "c5ae5eceafeae7b52de7bae039c4f69f193ab5ed6faea49864ade88f92a4f37c"
      define_method(:install) do
        bin.install "admiral-server"
      end
    end
  end
end
